### ISSUE TITLE
retrieve! for VideoReader{NO_TRANSCODE} does nothing

### ISSUE THREAD

**Issue by tibaes** [JuliaIO/VideoIO.jl#111]
I am trying to get a NO_TRANCODE image, however read / retrieve returns a Void.
Reading the code I found weird that retrieve! does not return the buf.

```julia
function retrieve!{T<:EightBitTypes}(r::VideoReader{NO_TRANSCODE}, buf::VidArray{T})
    while !have_frame(r)
        idx = pump(r.avin)
        idx == r.stream_index0 && break
        idx == -1 && throw(EOFError())
    end

    if !bufsize_check(r, buf)
        error("Buffer is the wrong size")
    end
end
```

I believe that this function does nothing on practice, as there is no copy of the image buffer to buf; neither this buffer is returned.

**Comment by kmsquire** [comment]
Still an issue--this was never completely implemented, it seems.  Mea culpa!
