### ISSUE TITLE
Integrate with FileIO?

### ISSUE THREAD

**Issue by tbenst** [JuliaIO/VideoIO.jl#118]
It would be nice to use the same functions for opening videos, rather than learning a new API. Perhaps  `open(*.mp4)` should call `VideoIO.open` and `display(AVInput)` should call `VideoIO.playvideo`?

**Comment by kmsquire** [comment]
I've thought about this in the past, and it would probably work if you only want one stream (presumably video) from the input.  It would be a little more challenging if you wanted other streams, but there's not much support here yet for other streams anyway...

Of course, there are probably more important changes that should happen first.  In particular, this package doesn't yet support any version of ffmpeg starting with 3.0...  I've made more than one attempt at this, but have been getting stuck at calling out to the image conversion step, and I haven't had the time recently to look at it. :-(

**Comment by IanButterworth** [comment]
Giving this a go over in https://github.com/JuliaIO/FileIO.jl/pull/319

**Comment by IanButterworth** [comment]
Now available in FileIO 1.7.0
