### ISSUE TITLE
BinaryProvider for FFMPEG

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/VideoIO.jl#120]
I'm not a 100% sure why I'm doing this to myself, but I'm working on a binarybuilder for ffmpeg.
Guess I thought it will be easy enough to get one builder working per day in the background :D 
Linux from scratch has been a great resource to figure out what to get where:
http://www.linuxfromscratch.org/blfs/view/svn/multimedia/ffmpeg.html

 - [x] [libass](https://github.com/JuliaIO/LibassBuilder)
 - [x] [fdk-aac](https://github.com/SimonDanisch/FDKBuilder)
 - [x] [NASM](https://github.com/SimonDanisch/NASMBuilder)
 - [x] [Fribidi](https://github.com/SimonDanisch/FribidiBuilder)
 - [x] [FreeType](https://github.com/JuliaGraphics/FreeTypeBuilder)
 - [x] [LAME](https://github.com/SimonDanisch/LAMEBuilder) OSX + Windows problems
 - [x] [Theora](https://github.com/SimonDanisch/TheoraBuilder) MUSL + ARM + Windows problems
 - [x] [Vorbis](https://github.com/JuliaIO/LibVorbisBuilder/)
 - [x] [Opus](https://github.com/SimonDanisch/OpusBuilder)
 - [x] libvpx
 - [x] x264
 - [x] x265
 - [x] yasm

Any help is much appreciated!

cc: @staticfloat

**Comment by timholy** [comment]
I wonder if this might help with #114 (which is kindof in the same category, but surely not as bad...)

I am *not* particularly useful when it comes to binary dependencies, unfortunately. But if you have specific questions, don't hesitate to post them. If nothing else the process of typing them out will probably cause you to realize the answer :stuck_out_tongue_winking_eye:

**Comment by staticfloat** [comment]
[Excellent, my young padawan](https://www.youtube.com/watch?v=67h8GyNgEmA).

When you run into problems, please open issues on your own build repositories with example errors, and ping me.

**Comment by jpsamaroo** [comment]
I haven't yet had the pleasure of working with BinaryBuilder, and I'd very much like to change that. @SimonDanisch do you have a recommendation on which of the remaining dependencies I should start working on a builder repo for?

**Comment by jpsamaroo** [comment]
I've decided to start working on BB repos for x264 and x265, without yasm support for now (because I encountered errors on every platform other than Linux 64-bit glibc when trying to build it). However, yasm will be required for libvpx at a minimum, so if someone can take a shot at getting that working, then that would be wonderful :smile:

**Comment by staticfloat** [comment]
Did you put your YASM work up on a repository somewhere?

**Comment by jpsamaroo** [comment]
Not yet, but I will when I get back to my computer in about 2 hours. I
didn't really try terribly hard to try to fix the non-working builds, but I
think I now know a way around the errors I'm getting.


On Aug 19, 2018 at 6:58 PM, <Elliot Saba <notifications@github.com>> wrote:

Did you put your YASM work up on a repository somewhere?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kmsquire/VideoIO.jl/issues/120#issuecomment-414165287>,
or mute the thread

**Comment by jpsamaroo** [comment]
https://github.com/jpsamaroo/YasmBuilder (fails pretty much everywhere, from the wiki page it also probably doesn't support non-x86/x86-64 targets)
https://github.com/jpsamaroo/x264Builder (Builds on all the things!)
https://github.com/jpsamaroo/x265Builder (Fails on ARM, PPC, Windows i686)

Note that x264 and x265 are built **without** yasm support, as I didn't want to rely on it right now in its very sorry state. I fully intend to add that back in once it's working on more than 2 targets...

**Comment by jpsamaroo** [comment]
First attempt at the whole thing, currently builds with most everything disabled on x86_64-linux-glibc: https://github.com/jpsamaroo/FFMPEGBuilder/. I'm working on enabling all the above dependencies, and then getting everything to build on every platform.

**Comment by rdeits** [comment]
Would this switch also make turning on precompilation easier? If we're using BinaryProvider, then presumably we don't need all the special logic to conditionally load the right version of ffmpeg support, right?

**Comment by jpsamaroo** [comment]
I'd imagine that it'd at least make things easier, since we'd know ahead of time what code will be enabled. However, I think the precompilation issues were mostly related to how VideoIO loads dependencies (specifically ImageView).

**Comment by rdeits** [comment]
I think I fixed the ImageView loading issues over in https://github.com/kmsquire/VideoIO.jl/pull/125 so we might be closer than we think :slightly_smiling_face:

**Comment by rdeits** [comment]
Heh, I'm starting to understand your pain w.r.t YASM. I attempted to add a Windows build and got absolutely nowhere. I've posted over in the bindeps2 slack to see if there's any way forward.

**Comment by ianshmean** [comment]
With #159 BinaryProvider is now used, where:

- Linux x86_64 <= provided via BinaryBuilder
- Windows 32/64 <= provided via https://ffmpeg.zeranoe.com/builds/
- MacOS <= provided via https://ffmpeg.zeranoe.com/builds/

I'd personally love to get this working on aarch64, so I'm wondering how things stand now w.r.t. the list in the first comment @SimonDanisch @jpsamaroo. In particular how many things are blocking ARM?

**Comment by ianshmean** [comment]
aaaand with #176 the FFMPEGBuilder pipeline is used properly, with only freebsd outstanding (and some precision bugs on ARM).

**Comment by SimonDanisch** [comment]
beautiful :) Glad I good jumpstart this!!!

**Comment by ianshmean** [comment]
It felt like a proper relay race..
