### ISSUE TITLE
Version choice of ffmpeg

### ISSUE THREAD

**Issue by hearnsj** [JuliaIO/VideoIO.jl#129]
At least on Windows there seems to be a reliance on specific versions of ffmpeg which are no longer available. Version 2.2.3 is no longer available for download.
Look at https://ffmpeg.zeranoe.com/builds/win64/shared/
I suggest using   https://ffmpeg.zeranoe.com/builds/win64/shared/ffmpeg-latest-win64-shared.zip

OK, this puts us at risk of an update which creates a breaking change. But surely this would be picked up in the tests?

**Comment by kmsquire** [comment]
Made obsolete by the recent move to binary provider.
