### ISSUE TITLE
Move to JuliaIO?

### ISSUE THREAD

**Issue by ianshmean** [JuliaIO/VideoIO.jl#137]
@kmsquire: I set up a #video channel on the julia slack, and in there @SimonDanisch and I discussed moving this over to https://github.com/JuliaIO to help promote its use?

I also suggested I could do a tidy up of the <v0.7 issues, and it would be good to put together an updated priority list/roadmap for ideas that are still relevant

**Comment by kmsquire** [comment]
Hi @ianshmean, thanks for taking the initiative here!  I think that sounds good.  I just posted a note at https://github.com/orgs/JuliaIO/teams/core, and barring any concerns, I'll move this repo to `JuliaIO` within a few days (as I noted on Slack).

**Comment by kmsquire** [comment]
Repo has been transferred, update has been submitted to `METADATA.jl` (https://github.com/JuliaLang/METADATA.jl/pull/20935).

**Comment by ianshmean** [comment]
Great, thanks @kmsquire!
