### ISSUE TITLE
Extend camera support

### ISSUE THREAD

**Issue by kmsquire** [JuliaIO/VideoIO.jl#14]
- [x] detection of camera devices
- [x] testing on OSX, Windows
- [ ] control of camera devices (contrast, etc.)
- [x] fliplr during display

**Comment by ianshmean** [comment]
While I haven't found any evidence of hope on Windows or MacOS for camera control, it can be achieved on Linux through [`v4l-utils`](https://git.linuxtv.org/v4l-utils.git/about/) (which has a lot of deps, so would likely be a lot of work to provide through `BinaryBuilder`):

> Adjusting camera functions
> Brightness, zoom, focus, etc, can be adjusted with v4l2-ctl. Display all controls and their menus:
> 
> ```v4l2-ctl -L```
> Then adjust the value:
> 
> ```v4l2-ctl -c <option>=<value>```

https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by IanButterworth** [comment]
I think control of camera settings may have proven to be a bigger task for which the right solution remains unclear. 

Worth noting that there are scientific camera control packages out there for different vendors, like Spinnaker.jl

I think I'll close this as camera support appears stable in recent releases.
