### ISSUE TITLE
VideoIO on aarch64

### ISSUE THREAD

**Issue by hearnsj** [JuliaIO/VideoIO.jl#158]
I am installing VideoIO on a Jetson Nano board which has an RPi camera (nice!)
https://devblogs.nvidia.com/jetson-nano-ai-computing/

When I test VideoIO I always get cannot find library libavcodec
I have tried serveral branches. I have installed libavcodev57 and lots of other libs for AV.
The board runs Ubuntu 18.04 and is aarch64

Sorry to open a new issue, and I have asked this before.
Can someone patiently explain why the multitude of codec libraries - I suppose this reflects the codec which are available in older and more receont Linux distros.
Also where is the check made for libavcodec?  I am supposing there is a hard wired check to /usr/lib64 or something.
On ARM the library is:  /usr/lib/aarch64-linux-gnu/libavcodec.so

**Comment by ianshmean** [comment]
This should be functional now on master (and soon to be tagged)

**Comment by ianshmean** [comment]
@hearnsj I'm keen to hear if you've had any success on your Jetson Nano, if you happen to have tried in the last couple of weeks

**Comment by hearnsj** [comment]
My apologies. No progress - I will give it a try today.

**Comment by hearnsj** [comment]
I installed Julia version 1.1.1
Grrrr....

v1.1) pkg> add VideoIO#master
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Updating git-repo `https://github.com/JuliaIO/VideoIO.jl.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Libdl [8f399da3]:
 Libdl [8f399da3] log:
 ├─Libdl [8f399da3] has no known versions!
 └─restricted to versions * by VideoIO [d6d074c3] — no versions left
   └─VideoIO [d6d074c3] log:
     ├─possible versions are: 0.6.6 or uninstalled
     └─VideoIO [d6d074c3] is fixed to version 0.6.6

**Comment by hearnsj** [comment]
VideoIO v0.6.6 #master  builds fine and all tests pass on AARCH64  Jetson Nano

**Comment by ianshmean** [comment]
Awesome! Thanks for testing
