### ISSUE TITLE
duration is in microseconds, not milliseconds

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/VideoIO.jl#162]
Fixed by #161 

Checkout that PR. I *think* it's my fault, so it's only fitting I try and fix it. Sorry about that. 

Just gonna go ahead and ping you @ianshmean since this is an easy fix for a silent and evil (albeit not life threatening) bug. Hope that's OK.

**Comment by ianshmean** [comment]
Thanks! merged with #161
