### ISSUE TITLE
Missing AVCodecContext field `crf`

### ISSUE THREAD

**Issue by ianshmean** [JuliaIO/VideoIO.jl#173]
With the ffmpeg executable, setting the `crf` field is a pretty nice way to control video quality, (see [here](https://trac.ffmpeg.org/wiki/Encode/H.264) for an explanation) but while it's listed on the ffmpeg docs, it's not in the VideoIO `AVCodecContext` struct. 

Does that mean clang missed it, or were those structs manually assembled?

**Comment by kmsquire** [comment]
I don’t see crf here:  

https://ffmpeg.org/doxygen/4.1/structAVCodecContext.html

Where did you see it in the docs?

**Comment by ianshmean** [comment]
Turns out I was looking at a very old (0.8) version doc, where `crf` used to be a field of `AVCodecContext`: https://ffmpeg.org/doxygen/0.8/structAVCodecContext.html

And from [this](https://ffmpeg.zeranoe.com/forum/viewtopic.php?t=2417) it looks like `crf` is passed as an argument into `priv_data` via something like:
```av_opt_set(c->priv_data, "crf", "1", AV_OPT_SEARCH_CHILDREN);```

Will test and report back

**Comment by ianshmean** [comment]
This is now working over in #172
