### ISSUE TITLE
loglevel

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/VideoIO.jl#184]
It would be nice to set the `loglevel` to, say, `fatal` to avoid overzealous warnings about:
```julia
using VideoIO
file = download("https://vision-group-temporary.s3.amazonaws.com//a.MTS")
f = openvideo(file)
seek(f, 30.0)
```
spits out this:
```julia
[h264 @ 0x417e940] reference picture missing during reorder
[h264 @ 0x417e940] Missing reference picture, default is 2147483647
```

**Comment by ianshmean** [comment]
I agree that we should suppress messages like this. There's one that pops up during `] test VideoIO` that's annoying.
`-loglevel fatal` is a `ffmpeg` executable-level setting. I can't immediately find one for the lower level functions. If you find one, please go ahead and submit a PR!

**Comment by yakir12** [comment]
I'm blindly browsing in the ffmpeg git repo and trying to find clues. [This](https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff/cdf17cf92b0f9c02951b7ea25d6a150000282bdf) seems relevant. Apparently we should be able to set this `FFREPORT` to 8 for showing only fatal errors (or `-8` for being totally silent). I don't know where or how but this is what it would look like:  
```
FFREPORT=level=8
```

**Comment by yakir12** [comment]
We basically need to set the **environment variable** `FFREPORT` to one of the following nummerical values:
‘quiet, -8’

    Show nothing at all; be silent. 
‘panic, 0’

    Only show fatal errors which could lead the process to crash, such as an assertion failure. This is not currently used for anything. 
‘fatal, 8’

    Only show fatal errors. These are errors after which the process absolutely cannot continue. 
‘error, 16’

    Show all errors, including ones which can be recovered from. 
‘warning, 24’

    Show all warnings and errors. Any message related to possibly incorrect or unexpected events will be shown. 
‘info, 32’

    Show informative messages during processing. This is in addition to warnings and errors. This is the default value. 
‘verbose, 40’

    Same as info, except more verbose. 
‘debug, 48’

    Show everything, including debugging information. 
‘trace, 56’

I have no idea how...

**Comment by giordano** [comment]
`ENV["FFREPORT"] = "8"`

**Comment by yakir12** [comment]
> ENV["FFREPORT"] = "8"

didn't work (for me).

**Comment by yakir12** [comment]
Maybe it needs to be specified in another environment than `ENV`.

**Comment by giordano** [comment]
> didn't work (for me).

Please, be more clear about what "didn't work" means.

**Comment by yakir12** [comment]
Oh, for sure, sorry. 
I tried to do something like this:
```julia
ENV["FFREPORT"] = "8"
using VideoIO
f = openvideo(file)
seek(f, s)
```
and it still printed out warnings. 

I'll be able to post a MWE tomorrow morning.

**Comment by giordano** [comment]
I do see a different output when setting the environment variable
```
julia> withenv(VideoIO.execenv) do
           join(VideoIO.collectexecoutput(`$(VideoIO.ffmpeg)`))
       end
"ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 4.8.5 (GCC)  configuration: --enable-cross-compile --cross-prefix=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu- --arch=x86_64 --target-os=linux --sysinclude=/workspace/destdir/include --pkg-config=/usr/bin/pkg-config --pkg-config-flags=--static --prefix=/workspace/destdir --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --extra-libs=-lpthread --enable-gpl --enable-version3 --enable-nonfree --disable-static --enable-shared --disable-debug --disable-doc --enable-avresample --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libvpx --enable-encoders --enable-decoders --enable-muxers --enable-demuxers --enable-parsers --extra-cflags=-I/workspace/destdir/include --extra-ldflags=-L/workspace/destdir/lib  libavutil      56. 22.100 / 56. 22.100  libavcodec     58. 35.100 / 58. 35.100  libavformat    58. 20.100 / 58. 20.100  libavdevice    58.  5.100 / 58.  5.100  libavfilter     7. 40.101 /  7. 40.101  libavresample   4.  0.  0 /  4.  0.  0  libswscale      5.  3.100 /  5.  3.100  libswresample   3.  3.100 /  3.  3.100  libpostproc    55.  3.100 / 55.  3.100Hyper fast Audio and Video encoderusage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...Use -h to get full help or, even better, run 'man ffmpeg'"

julia> withenv(VideoIO.execenv, "FFREPORT" => "8") do
           join(VideoIO.collectexecoutput(`$(VideoIO.ffmpeg)`))
       end
"ffmpeg started on 2019-06-12 at 22:26:10Report written to \"ffmpeg-20190612-222610.log\"ffmpeg version 4.1 Copyright (c) 2000-2018 the FFmpeg developers  built with gcc 4.8.5 (GCC)  configuration: --enable-cross-compile --cross-prefix=/opt/x86_64-linux-gnu/bin/x86_64-linux-gnu- --arch=x86_64 --target-os=linux --sysinclude=/workspace/destdir/include --pkg-config=/usr/bin/pkg-config --pkg-config-flags=--static --prefix=/workspace/destdir --sysroot=/opt/x86_64-linux-gnu/x86_64-linux-gnu/sys-root --extra-libs=-lpthread --enable-gpl --enable-version3 --enable-nonfree --disable-static --enable-shared --disable-debug --disable-doc --enable-avresample --enable-libass --enable-libfdk-aac --enable-libfreetype --enable-libmp3lame --enable-libvorbis --enable-libx264 --enable-libx265 --enable-libvpx --enable-encoders --enable-decoders --enable-muxers --enable-demuxers --enable-parsers --extra-cflags=-I/workspace/destdir/include --extra-ldflags=-L/workspace/destdir/lib  libavutil      56. 22.100 / 56. 22.100  libavcodec     58. 35.100 / 58. 35.100  libavformat    58. 20.100 / 58. 20.100  libavdevice    58.  5.100 / 58.  5.100  libavfilter     7. 40.101 /  7. 40.101  libavresample   4.  0.  0 /  4.  0.  0  libswscale      5.  3.100 /  5.  3.100  libswresample   3.  3.100 /  3.  3.100  libpostproc    55.  3.100 / 55.  3.100Hyper fast Audio and Video encoderusage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...Use -h to get full help or, even better, run 'man ffmpeg'"
```
However, I think that the variable is simply not doing what you expect, because the result is to write a log file (the report), not to suppress stdout printings

**Comment by yakir12** [comment]
OK, I'm a few days late with this MWE, but here's the behavior I mean (and I'll add this to the initial message too):
```julia
using VideoIO
file = download("https://vision-group-temporary.s3.amazonaws.com//a.MTS")
f = openvideo(file)
seek(f, 30.0)
```
spits out this:
```
[h264 @ 0x417e940] reference picture missing during reorder
[h264 @ 0x417e940] Missing reference picture, default is 2147483647
```
How can we avoid such output?

**Comment by giordano** [comment]
> How can we avoid such output?

Not with `FFREPORT`

**Comment by ianshmean** [comment]
@yakir12 See what you make of #189 

I'm undecided about whether the info message at import is necessary..

**Comment by ianshmean** [comment]
#189 #191 Merged!
