### ISSUE TITLE
Storage Aspect Ratio: SAR

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/VideoIO.jl#185]
The SAR in some videos ([example file](https://s3.eu-central-1.amazonaws.com/vision-group-file-sharing/Fun%20Stuff/a.MTS)) is not always 1. In such cases, the read image gets warped:
![1](https://user-images.githubusercontent.com/3281957/59359281-58d6e080-8d2e-11e9-9ca6-12e8def9228d.jpg)
The black window should have been perfectly circular (not an ellipse).

When extracting images from a video, I used to fix this with: 
```
ffmpeg <...> -vf scale=sar"*"iw:ih <...>
```
And in fact, that works no matter what the SAR is (I think it costs time though). 

What are your opinions on that...? What would be the best way to deal with this problem? Is this relevant to all 3 PAR, SAR, and DAR? 

I'll just add that when playing the video in, say, `mpv`, the image is displayed correctly. So I guess that the "correct thing to do" is to somehow correct for not-equal-to-one SARs...

**Comment by yakir12** [comment]
Here's a MWE:
```julia
using VideoIO, ImageView
file = download("https://s3.eu-central-1.amazonaws.com/vision-group-file-sharing/Fun%20Stuff/a.MTS")
f = openvideo(file)
img = read(f)
imshow(img)
```
Which produces this warped image:
![tmp](https://user-images.githubusercontent.com/3281957/59362306-85d9c200-8d33-11e9-9044-fdb3ac7c3195.jpg)

**Comment by ianshmean** [comment]
Great question. I think this is an image display issue, rather than something that should change the underlying image array.

Also, it's worth specifying whether we're talking about the image aspect ratio, or the data aspect ratio. i.e. most videos might have a 4:3 image aspect ratio, but square pixels, so a data aspect ratio of 1 is most common.

I've made a PR (https://github.com/JuliaIO/VideoIO.jl/pull/186) that supports playing back of videos in Makie using the optional `pixelaspectratio` which is the squareness of the pixel aspect ratio, width/height, where square pixels would be 1.0:
```julia
using Makie, VideoIO
playvideo(f, pixelaspectratio=1.0)
```

As for the `ImageView` `imshow()` method for viewing a single frame, `ImageView` is broken due to `Gtk.jl` being broken on MacOS Mojave, so I can't really test it.

**Comment by yakir12** [comment]
I am mostly concerned with the aspect ratio of the pixels (data aspect ratio == pixel aspect ratio == SAR), the very ratio that causes the extracted images to be warped (since the pixels are always assumed to be square). But I might get the terminology wrong ← correct me if I'm wrong (like, are there any other pitfalls?).

A decision to leave any corrective warping to the user is reasonable. But we need some way to detect the SAR, and/or warn when it's not equal to one. Especially since it is (widely) assumed to be equal to one and rarely isn't.  

The background for all of this is that I'm extracting pixel coordinates from the videos, calibrate those to real-world coordinates, and therefore need to know if these are skewed somehow.

**Comment by ianshmean** [comment]
SAR is currently read, but I'm not sure how well it's handled or propagated. If you have an idea for how to handle it, I think you'd be in a better position to suggest a PR than me.
https://github.com/JuliaIO/VideoIO.jl/blob/4682a8a569f1aa9fea1993725cf80f71a87fd771/src/avio.jl#L267-L269

**Comment by yakir12** [comment]
Well, it seems from [this](https://github.com/FFmpeg/FFV1/issues/109) that some videos will have zero/unknown numerators or denumerators. `ffmpeg` deals with this by setting the numerator to zero and the denumerator to 1. I suggest we keep the current configuration. When the SAR truly isn't equal to 1 it won't equal to zero either. I therefore conclude that this is pretty good for me:
```julia
f = openvideo(file)
sar = f.aspect_ratio
if sar ≠ 0 && sar ≠ 1
    < deal with a freaky SAR >
end
```

But yea, since SAR in the wild is not always trust worthy (when missing or equal to zero) then we can't do much with it. Eventually maybe some of this discussion should make it to the docs... Feels kind of esoteric though.

**Comment by ianshmean** [comment]
Yeah, definitely something for the docs!
The readme is starting to feel bloated.. perhaps it's time to start some proper docs..

**Comment by yakir12** [comment]
I'll gladly parse this into some section in the docs (add a convenience function if you like), but a major change like adding documenter etc, I'll leave that to you...

**Comment by ianshmean** [comment]
Cool. Go ahead and add it to the readme so we don't forget it when we refactor into proper docs

**Comment by yakir12** [comment]
sure-first thing-tomorrow.

**Comment by yakir12** [comment]
OK, now I think the `playvideo` function should detect and use the correct aspect ratio. I'll work on a proper PR tomorrow. Nice!

**Comment by ianshmean** [comment]
I've just merged #186 but it occurred to me afterwards that it would be good to add a test for SAR.

**Comment by yakir12** [comment]
Done https://github.com/JuliaIO/VideoIO.jl/pull/190

**Comment by ianshmean** [comment]
Merged!
