### ISSUE TITLE
Inconsistent time units

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/VideoIO.jl#197]
This is partly my own fault, but `get_duration` returns `Dates.Microsecond`s, `seek` accepts floats that are supposed to be seconds, the new `gettime` also returns seconds as floats. I feel we should standardize this somewhat. As I see it our options are:
1. Keep everything as floats and indicate it's all seconds. This is a bit of a shame -- Julia `Dates` stdlib is really solid, we should make use of it.
2. The smallest [functionally distinguishable](https://discourse.julialang.org/t/differences-smaller-than-dates-milliseconds-are-ignored) unit of time in the stdlib `Dates` is `Millisecond`. We can accommodate for any `Dates.TimePeriod` down to a `Millisecond`, `Dates.CompoundPeriod`s, and/or `<:Real` as seconds. As to return types, maybe we should therefore return the smallest unit of time we'll deal with: `Millisecond`s.    
3. Same as point number 2 above but depend on [TimesDates.jl](https://github.com/JeffreySarnoff/TimesDates.jl) to support any time period down to a nanosecond (instead of millisecond).

If interested, I can PR this.

**Comment by ianshmean** [comment]
See #195  where duration is returned in seconds

**Comment by yakir12** [comment]
#195 resolves the inconsistency so we can close this now (when that PR is merged etc). 

About not making use of the `Dates` stdlib: is it true or false that all videos have a smallest "unit of time" defined in them? If it's false and the difference between two sequential time stamps can be any rational number (so not 1e-6 or 1e-5 but 0.001276239725216242385347234621637348), then yea, your float seconds is the best idea. But if such a thing exist then we can take advantage of it and use `Dates`.

**Comment by yakir12** [comment]
#195 has been merged, so I'm closing this, but...
I still think it would be better to work with `Dates.TimePeriod` than arbitrary floats. Apart from the ambiguity about the unit (is it seconds? Milliseconds? etc) it would also make indexing into a video much more reliable (a float's accuracy is limited, a TimePeriod is absolute, which is partly why we don't have float time periods in Julia).
