### ISSUE TITLE
Backend discussion

### ISSUE THREAD

**Issue by kmsquire** [JuliaIO/VideoIO.jl#2]
- [x] Explore avbin
- [x] BinDeps integration
- [x] Support more recent versions of libav/ffmpeg
- [x] At load time, determine which wrapper version to load.
- [x] ~~Probably switch to using StrPack for everything but reading/decoding frames.  Dealing with struct pointers directly through Julia is rather painful right now, and some of the larger structs created by Clang ( e.g., `immutable Array_Uint8_1024`) take way too long to compile and instantiate.  (I can provide more details if needed).~~
- [ ] Clean up and remove unnecessary functions and types.  Right now, almost everything is included, because that was easiest to get started, but large chunks are probably not needed.

cc: @ihnorton @lucasb-eyer @timholy

**Comment by IanButterworth** [comment]
Doing a bit of a tidy up, so I will close this. Fun to read back the early discussions :)
