### ISSUE TITLE
Image reading demo has incorrect reading format

### ISSUE THREAD

**Issue by dennisli97** [JuliaIO/VideoIO.jl#204]
Image reading in demo is reading as bite string 
Consider reading image through fileIO 

using FileIO
img = load("myphoto.png")

**Comment by ianshmean** [comment]
Ah, thanks. I've corrected it on master [here](https://github.com/JuliaIO/VideoIO.jl/commit/695c8a674731a8f87808f6b494391ade887458ba), and dev docs will update when that finishes building
