### ISSUE TITLE
Video exported with standard settings is stuttering on MacOS Mojave

### ISSUE THREAD

**Issue by jkrumbiegel** [JuliaIO/VideoIO.jl#208]
I can play the resulting mp4 file back with VLC, although it does exhibit a small jump over the last couple frames when it loops. Preview and Quicktime Player play the file with a horribly messed up frame order, basically the frames are not played back in the correct sequence but jump forward around 4 frames and then go back 3, etc. Here's an example video of that:

https://i.imgur.com/NxXvEcp.mp4

My settings are just the standard ones for medium quality, although I also tried with this `[:priv_data => ("crf"=>"22","pix_fmt"=>"yuv420p", "profile:v"=>"baseline", "level"=>"3")]` but it didn't make a difference.

**Comment by ianshmean** [comment]
This has been seen before but we haven’t found a solution yet. 

See open PR #179

**Comment by jkrumbiegel** [comment]
Ah I see, thank you, should I find out anything helpful I'll post it over there

**Comment by IanButterworth** [comment]
Should be fixed in v0.9
