### ISSUE TITLE
Documentation error (iterative encoding)

### ISSUE THREAD

**Issue by taigah** [JuliaIO/VideoIO.jl#213]
Hey,

I suspect that there is an issue with [this code](https://juliaio.github.io/VideoIO.jl/stable/writing/#Iterative-Encoding-1). Shouldn't it be

```
...
firstimg = FileIO.load(imgnames[1])
...
    img = FileIO.load(imgname)
...
```

instead of "read"?

**Comment by IanButterworth** [comment]
Fixed
