### ISSUE TITLE
VideoIO.viewcam() does nothing

### ISSUE THREAD

**Issue by Roseck16** [JuliaIO/VideoIO.jl#214]
When I use the function viewcam() it appears to work, I even get an on light in my webcam, but it stays there forever.

I'm using Julia 1.2 and I'm on Windows 10 x64

**Comment by Roseck16** [comment]
So I upgraded to Julia 1.3 at now it threw some errors, about not having a proper backed (Makie and so) but I had to go back to 1.2 to solve those. Now still viewcam() and opencamera() don't do anything

**Comment by ianshmean** [comment]
@Roseck16 sorry I didn’t respond sooner. Given you closed this can I assume it’s now working for you?

**Comment by Roseck16** [comment]
Yes, sorry, It was a problem with my camera

**Comment by ianshmean** [comment]
Ah ok. Glad you got it fixed
