### ISSUE TITLE
Strange "noise points"?

### ISSUE THREAD

**Issue by yiyuezhuo** [JuliaIO/VideoIO.jl#243]
I found that `read` generates some "noise points" in the right region. More weirdly, it gives different results on Windows and Linux.

ffmpeg result (reference, both on Windows and Linux):

![image](https://user-images.githubusercontent.com/12798270/84290513-57750980-ab76-11ea-839c-afb9b7f8472f.png)

VideoIO on linux:
![image](https://user-images.githubusercontent.com/12798270/84290555-6491f880-ab76-11ea-9cca-ced4aa8556be.png)

VideoIO on Windows:
![image](https://user-images.githubusercontent.com/12798270/84290578-707dba80-ab76-11ea-8ec5-2e2ccc465d69.png)

Test video:
https://drive.google.com/file/d/1ThCzT_1PMkspxAktCY1bkvFFsG_IsNHc/view?usp=sharing

ffmpeg command:

```bash
ffmpeg -i out.mp4 frame%04d.png
```

VideoIO script:

```julia
using VideoIO
using FileIO

function fmt(x)
    s = string(x)
    "0"^(4-length(s)) * s
end

function split_frame(fname)
    io = VideoIO.open(fname)

    f = VideoIO.openvideo(io)

    img = read(f)

    let i=1
        while !eof(f)
            save("frame" * fmt(i) * ".png", img)
            i += 1
            read!(f, img)
        end
        save("frame" * fmt(i) * ".png", img)
    end
end

split_frame("out.mp4")
```

Do I need some extra options to avoid this? Or is there a "standard" format to make VideoIO work without such problems (The test video self is generated by ffmpeg with default parameter.)?

**Comment by yiyuezhuo** [comment]
I had a hard time to debug this and figure it out that it's due to [avpicture deprecated problem](https://github.com/JuliaIO/VideoIO.jl/blob/master/src/avio.jl#L298) (also see SO [quesion](https://stackoverflow.com/questions/35678041/what-is-linesize-alignment-meaning/35682306)). I compared VideoIO with [PyAV](https://github.com/PyAV-Org/PyAV), which returned the correct result, and finally got a solution. Maybe I will create a pull request to fix this, but it's not that minor though.

**Comment by ianshmean** [comment]
A PR would be very welcome!
