### ISSUE TITLE
Undocumented change to `read!` between VideoIO versions 0.7.1 and 0.7.2 causes errors

### ISSUE THREAD

**Issue by galenlynch** [JuliaIO/VideoIO.jl#253]
I have been using 0.7.1 for a while, but noticed that my client code is broken on master. After a bit of git-blaming, I found that [this line in commit eaf4dbc](https://github.com/JuliaIO/VideoIO.jl/blob/eaf4dbc41f0fa4880281c06060e8fc9d94460cd9/src/avio.jl#L438) (part of PR #245) is causing breakage for me, although I may have been abusing the API and it's just now come back to haunt me. 

Specifically, I mostly work with images and frames of movies in a "scan-line major", or image-x major, memory format as many libraries expect that, including FFMPEG itself. However, VideoIO instead mostly assumes a row major format, where rows of a matrix are equated with image y dimension. Until eaf4dc, I simply used the parent array underlying the `PermutedDimsArray` view returned by `VideoIO.read(r::VideoReader)`, and passed that parent array to subsequent calls to `VdeoIO.read!(r::VideoReader, arr::VidArray)` to read a video. 

While the documentation says nothing about what _type_ of array `VideoIO.read!` expects, the fact that `VidArray{T,N} = Union{Array{T,N},PermutedArray{T,N}}` led me to believe that passing it regular arrays was fine as far as the supported API was concerned, and obviously `read!` did not care since no permutation was being done, and in the end all the `read!` function was doing with `buf` was passing a pointer to the image-x major buffer to FFMPEG.

eaf4dc directly accesses the `parent` field of the `buf::VidArray` parameter, which is fine if `buf` is a `PermutedArray` but causes an error if it is the other portion of the `VidArray` union, namely a normal array. This line could be replaced by `parent(buf)`, which would work in either case, or could also just be eliminated since `pointer(buf) === pointer(parent(buf))`, and nothing else is done with the parent array. I'll make a PR that does the latter soon, but that does not address the potential breakage that users will experience if they check out VideoIO 0.7.2. I'm unsure how to fix that breakage, so I'm positing this issue independent of my upcoming PR that will fix the underlying bug. Also some clarification of what is considered supported behavior would probably help: is `read!` with normal arrays supported?

**Comment by ianshmean** [comment]
Ah.. Indeed, that was an unintended breakage. For your PR, adding unit test would be appreciated

**Comment by galenlynch** [comment]
I think the tests that I added cover both cases.
