### ISSUE TITLE
Documentation is from v0.6.10

### ISSUE THREAD

**Issue by Wikunia** [JuliaIO/VideoIO.jl#264]
I just saw that the documentation is only available for v0.6.10 whereas the most recent version is v0.8.1

You might want to add this line https://github.com/Wikunia/Javis.jl/blob/master/.github/workflows/TagBot.yml#L12
Into the TagBot.yml to make this work.

**Comment by ianshmean** [comment]
Yikes. Good spot. Thanks.
Is `DOCUMENTER_KEY` automatically provided or do we need to add it as a secret?

**Comment by Wikunia** [comment]
You need to add it as a secret. I think this method should help: https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#Documenter.documenter_key

**Comment by Wikunia** [comment]
Oh and it only creates a new folder when you have a new tag. It doesn't fix the problem directly. I think for that you basically have to build it locally for the version and push that to `gh-pages`.

**Comment by ianshmean** [comment]
- [x]  TagBot now set up to do docs (used this generator https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#travis-ssh)
- [x] v0.8.1 docs generated locally and updated #265 
- [ ] versions between v0.6.10 and 0.8.1 generated and uploaded (couldn't figure out an easy way to do this)

**Comment by ianshmean** [comment]
I'm going to close this as figuring out how to generate older docs is probably not worth the effort.
