### ISSUE TITLE
why the pwd?

### ISSUE THREAD

**Issue by yakir12** [JuliaIO/VideoIO.jl#288]
https://github.com/JuliaIO/VideoIO.jl/blob/67e7a6dc811338d86f8d09ac2cb96c9dfaf00ec8/src/encoding.jl#L228

why report that `"Video file saved: $(pwd())/$destfilename"` and not `"Video file saved: $destfilename"`? You're also assuming that the OS has a `/` for paths. Threw me off at least. Or maybe there is a good reason for it?

**Comment by ianshmean** [comment]
Good question. Looks to be in error. Perhaps it's just catering for if only a file name is provided.

**Comment by yakir12** [comment]
I see. Well, since that is not what the function does (i.e. it does not create a video at `joinpath(pwd(), destfilename)` nor does it delete a file at `joinpath(pwd(), srcfilename)`, then I suggest we remove that (PR #289).
