### ISSUE TITLE
Support video generation

### ISSUE THREAD

**Issue by kmsquire** [JuliaIO/VideoIO.jl#36]
Support for video generation exists in ffmpeg/libav; it just needs to be properly wrapped/enabled.

**Comment by perrutquist** [comment]
I've implemented video generation by simply piping PNG images into `ffmpeg -f image2pipe -i -`
Code can be found here: https://github.com/perrutquist/FFmpegPipe.jl
Feel free to copy it if you want.

**Comment by ianshmean** [comment]
H264-based grayscale & RGB video generation/encoding now provided as of `v0.6.4`
