### ISSUE TITLE
`sigatomic_end` throws error with VSCode Debugger

### ISSUE THREAD

**Issue by mrufsvold** [JuliaIO/VideoIO.jl#371]
`VideoIO.get_time_duration()` runs normally when I use it from the Julia REPL. However, when using the Julia Debugger in VSCode, it throws the following exception

```
sigatomic_end called in non-sigatomic region

Stacktrace:
 [1] close(avin::VideoIO.AVInput{String})
   @ VideoIO C:\Users\mrufsvold\.julia\packages\VideoIO\V24Bg\src\avio.jl:968
 [2] get_time_duration(file::String)
   @ VideoIO C:\Users\mrufsvold\.julia\packages\VideoIO\V24Bg\src\info.jl:45
```

It appears that PyCall had the [same problem](https://github.com/JuliaDebug/JuliaInterpreter.jl/issues/219), and they were able to resolve it  by replacing[ `sigatomic_(end|begin)` with `disable_sigint`](https://github.com/JuliaPy/PyCall.jl/pull/686). My understanding from reading their conversation is that `sigatomic_(end|begin)` is an internal function for Julia and `disable_sigint` is its the public API sibling.

I can put in a PR if the maintainers aren't opposed to the change for some reason!

**Comment by IanButterworth** [comment]
Closed by #372
