### ISSUE TITLE
VideoIO can't open some AV1 encoded mkv files

### ISSUE THREAD

**Issue by contradict** [JuliaIO/VideoIO.jl#373]
Originally reported on discourse [here](https://discourse.julialang.org/t/videoio-jl-can-t-seem-to-open-a-mkv-video/83875/4).

**Comment by contradict** [comment]
I opened a PR to get libaom into Yggdrasil [here](https://github.com/JuliaPackaging/Yggdrasil/pull/5125).

**Comment by contradict** [comment]
OK! Thanks to @giordano these two PR's are merged and this issue can be closed. Updating packages will get the latest FFMPEG_jll which is already compatible with the current VideoIO.

**Comment by IanButterworth** [comment]
Nice, thanks both!
