### ISSUE TITLE
Extracting frames from video exmple

### ISSUE THREAD

**Issue by philtomson** [JuliaIO/VideoIO.jl#38]
We need to extract frames from video (mpeg) and do some processing on each image (and eventually put them back together as a video stream). Primarily we want to do some comparisions between consecutive frames.

Is this sort of thing possible with VideoIO? Would it be possible to add an example that does something like this?

**Comment by IanButterworth** [comment]
Decoding and encoding is now well supported, with some simpler API's on the encoding side as of v0.9
