### ISSUE TITLE
GC'ing a VideoWriter without closing it first

### ISSUE THREAD

**Issue by Octogonapus** [JuliaIO/VideoIO.jl#404]
We are using VideoIO on a resource-constrained system and sometimes need to abort writing out a video. Running `close_video_out!` takes a long time in this case, presumably because it's writing out a bunch of frames to disk. Is it okay to skip this call and let the `VideoWriter` get garbage collected? Will all native resources still be freed? I ask because I noticed the implementation does some cleanup on the writer:
https://github.com/JuliaIO/VideoIO.jl/blob/a445dfcc999488111502649250b3dd9fe5f06914/src/encoding.jl#L114-L119

**Comment by galenlynch** [comment]
I think the finalizers will still run if the writer itself gets GC’d before it’s closed, but it might be worth testing. The code there is just cleaning up the resources allocated by the writer by removing the writer’s references to them.
