### ISSUE TITLE
Can we make VideoIO an IO only library!?

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaIO/VideoIO.jl#60]
Hi,
as I'm pretty much implementing the ImageView functionality over at GLVisualize, it's pretty annoying that I suddenly depend on Images, ImageView, TK, Cairo, etc, just by using VideoIO.
Would it make sense to put this functionality into some package like e.g. VideoView?!

Best,
Simon

**Comment by kmsquire** [comment]
Hi Simon, I'd be open to something like that. Unfortunately, I probably won't be able to work on it for the next week or so.

**Comment by timholy** [comment]
If you're effectively rewriting ImageView, I should share my notes on a planned-someday-when-I-have-time revamp. Not sure any of this will make sense (maybe even to me!), but here's the file I found on my laptop:

```
ImageView revamp notes:

- New view types: IVArray{T,N,(:X,:Y)}, IVArray{T,N,(:Y,:X)}, IVArray{T,N,(:X,:Y,:T)}, IVArray{T,N,(:Color,...)}.
  This should end all the need for slicing
- Don't allocate a new surface with each resize, just use the old one and a subset if necessary. Access the subset by BoundingBox
- Use traits. has_time() and size_time_known() (to include streaming VideoIO objects of unknown or infinite duration), has_pixels() (for function plotting, like fractals with infinite zoomability)
- Probably use Reactive for controls
- Think about state & containment more carefully. Support current usage, two panels displaying two images locked to a single set of controls, a toggle viewer, a display like stackviewer, a 3x3 grid with different z slices and a single t control.
- Or better not to use SubArrays in ImageView, and instead use a CartesianRange for specifying location?

Look at Holoviews for inspiration, http://ioam.github.io/holoviews.
```

**Comment by SimonDanisch** [comment]
Holoview looks interesting =)
Could be done with GLVisualize reeelatively easily... I just need to be carefull with hacking in new futures which don't generalize well.
Where do you use slicing so far? Or is that for volume images?
Reactive is actually surprisingly well fitted for video streams. I'm using a Reactive signal of images for displaying videos and its completely smooth ;) With some additional work we could paramertrice the signal more, to allow for pause, fast forward/backward and stepping to specific times.
How would I currently jump to a specific time point in a video stream!?

**Comment by timholy** [comment]
Yes, slicing is for volume images. And as you say, time-jumping only works for something for which you have random access. Both of which are true for data sets I care a lot about, but generalization is a good thing.

**Comment by timholy** [comment]
(Oh, and I didn't mean to suggest this as a TODO list, but merely "if you're thinking about the problem freshly, here are some things I wish I had considered more carefully at an earlier stage.")

**Comment by ianshmean** [comment]
I think it would be wise to revisit this idea.. Making VideoIO IO-only would make a lot of sense. 

@SimonDanisch @timholy What would be the best/simplest way to provide external means to support the following:

https://github.com/JuliaIO/VideoIO.jl/blob/aa60c982d1ddbe42583b2cf21b37606b8a590ea4/src/VideoIO.jl#L75-L104

**Comment by timholy** [comment]
What about returning the movie as a [StreamingContainer](https://github.com/JuliaImages/ImageAxes.jl/blob/65ac3b7581df2a91d6429f426a385e8486aa3de6/src/ImageAxes.jl#L196-L239)? ImageView also has [support for non-AbstractArrays](https://github.com/JuliaImages/ImageView.jl/blob/fa205f4833d19bcdcaa746106178bdfbaa0357ff/src/ImageView.jl#L237-L262), so hopefully pretty much everything is ready? I'd of course be happy to entertain PRs that add any missing functionality.

**Comment by ianshmean** [comment]
Closing as ImageView is now no longer a dep as of #160 where also given current issues in `ImageView`, we've moved to `Makie`.
