### ISSUE TITLE
ERROR: `read!` has no method matching

### ISSUE THREAD

**Issue by mitkoge** [JuliaIO/VideoIO.jl#68]
Hello, its my first try on VideoIO and julia so it my seem trivial to you.

---

 julia> versioninfo()
Julia Version 0.3.11
Commit 483dbf5 (2015-07-27 06:18 UTC)
Platform Info:
  System: Linux (x86_64-linux-gnu)
  CPU: Intel(R) Atom(TM) CPU D525   @ 1.80GHz
  WORD_SIZE: 64
  BLAS: libopenblas (NO_LAPACK NO_LAPACKE DYNAMIC_ARCH NO_AFFINITY Atom)
  LAPACK: liblapack.so.3
  LIBM: libopenlibm
  LLVM: libLLVM-3.3

julia> using Images

julia> import ImageView
Warning: could not import Base.Text into Tk
WARNING: Color is deprecated, please use Colors instead. See https://github.com/JuliaGraphics/Colors.jl
Warning: could not import Base.add into Winston

julia> import VideoIO

julia> VideoIO.versioninfo()
Using libav
AVCodecs version 54.35.0
AVFormat version 54.20.4
AVUtil version 52.3.0
SWScale version 2.1.1
AVDevice version 53.2.0
AVFilters version 3.3.0

julia> f = VideoIO.opencamera()
VideoReader(...)

julia> img = read(f, Image)
RGB Image with:
  data: 160x120 Array{RGB{UfixedBase{Uint8,8}},2}
  properties:
    spatialorder:  x y

julia> canvas, _ = ImageView.view(img)
(ImageCanvas,ImageSlice2d: zoom = BoundingBox(0.0,160.0,0.0,120.0))

julia> read!(f, img)
ERROR: `read!` has no method matching read!(::VideoReader{true}, ::Array{RGB{UfixedBase{Uint8,8}},2})
 in read! at /home/mitko/.julia/v0.3/VideoIO/src/avio.jl:671

julia> ImageView.view(canvas, img)
(ImageCanvas,ImageSlice2d: zoom = BoundingBox(0.0,160.0,0.0,120.0))

julia> close(f)

---

i can call read(f, Image) as many times i like and it takes an image but read! fails.

**Comment by kmsquire** [comment]
Thanks for the report. I'll try to take a look tomorrow.

**Comment by kubaroth** [comment]
Just run into the same issue with the latest version 0.0.14. Keno's patch seems to resolves the problem. Just wondering  if we can pull it into master?

**Comment by kmsquire** [comment]
The passes failed with Keno's patch, though I don't think it's his fault.  I'll look into it.

**Comment by kubaroth** [comment]
Curious what's causing this patch to fail? Is the error log available? 
Thanks.

**Comment by ianshmean** [comment]
Closing as this seems outdated and likely fixed by now
